name: CI
on: [ push, pull_request ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - run: npm install
      - run: npm run lint --if-present
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - run: npm install
      - run: npm run coverage --if-present
