name: CI
on: [ push, pull_request ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
      - run: npm install
      - run: npm run lint --if-present
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
      - run: npm install
      - run: npm run coverage --if-present
